name: CI - Automatización QA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Hacer checkout del código
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. Configurar Java
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Instalar dependencias y compilar (Maven)
      - name: Instalar dependencias y compilar
        run: mvn clean install -DskipTests

      # 4. Ejecutar tests UI + API en BrowserStack
      - name: Ejecutar tests UI + API
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: mvn test

      # 5. Generar reportes Serenity
      - name: Generar reportes Serenity
        run: mvn serenity:aggregate

      # 6. Guardar reportes como artefactos descargables
      - name: Guardar reportes
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: target/site/serenity

      # 7. Guardar screenshots (opcional)
      - name: Guardar screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: target/site/serenity/screenshots

